name = "PiCamera"
uuid = "8d255f71-f774-44b7-a103-e570ea10f53b"
authors = ["yakir12 <12.yakir@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
